name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - pip:
    - azureml-defaults==1.38.0
    - joblib==1.0.1
    - torch==1.9.0
    - transformers==4.21.1
    - ipadic==1.0.0
    - fugashi==1.1.2
